version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      hashicorp:
        patterns:
          - "github.com/hashicorp/*"
      grpc-protobuf:
        patterns:
          - "google.golang.org/grpc"
          - "google.golang.org/protobuf"
          - "google.golang.org/genproto/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
