variable "altinity_api_token" {
  type        = string
  sensitive   = true
  description = "ACM API token. Alternatively set ALTINITYCLOUD_API_TOKEN."
}

variable "environment_name" {
  type        = string
  description = "Name of the existing Altinity.Cloud environment to launch into."
}

variable "clickhouse_stream" {
  type        = string
  default     = "altinity-stable"
  description = "ClickHouse build stream: altinity-stable, altinity-antalya (Project Antalya), or upstream."

  validation {
    condition     = contains(["altinity-stable", "altinity-antalya", "upstream"], var.clickhouse_stream)
    error_message = "clickhouse_stream must be one of: altinity-stable, altinity-antalya, upstream."
  }
}

# The ClickHouse version is discovered via the altinity_clickhouse_versions data
# source (latest available), and admin/user passwords are generated by
# random_password in main.tf — so there are no further variables to set.
