// Copyright (c) Gorgias, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/specgen; DO NOT EDIT.
// Source: internal/acm/wire/reference.json (vendored OpenAPI spec).
// Regenerate with: go generate ./...

package wire

// Endpoint describes a single ACM REST operation resolved from the OpenAPI
// spec by operationId.
type Endpoint struct {
	OperationID string
	Method      string
	// PathTemplate uses OpenAPI-style {name} placeholders.
	PathTemplate string
	// PathParams lists the {name} placeholders in template order.
	PathParams []string
}

// Endpoints is the registry of allowlisted ACM operations the provider
// consumes. Keyed by operationId. Generated from reference.json.
var Endpoints = map[string]Endpoint{
	"ClusterLaunch": {
		OperationID:  "ClusterLaunch",
		Method:       "POST",
		PathTemplate: "/environment/{environment}/clusters/launch",
		PathParams:   []string{"environment"},
	},
	"ClusterList": {
		OperationID:  "ClusterList",
		Method:       "GET",
		PathTemplate: "/environment/{environment}/clusters",
		PathParams:   []string{"environment"},
	},
	"ClusterShow": {
		OperationID:  "ClusterShow",
		Method:       "GET",
		PathTemplate: "/cluster/{id}",
		PathParams:   []string{"id"},
	},
	"ClusterStatus": {
		OperationID:  "ClusterStatus",
		Method:       "GET",
		PathTemplate: "/cluster/{cluster}/status",
		PathParams:   []string{"cluster"},
	},
	"ClusterRescale": {
		OperationID:  "ClusterRescale",
		Method:       "PUT",
		PathTemplate: "/cluster/{id}/rescale",
		PathParams:   []string{"id"},
	},
	"ClusterUpgrade": {
		OperationID:  "ClusterUpgrade",
		Method:       "PUT",
		PathTemplate: "/cluster/{id}/upgrade",
		PathParams:   []string{"id"},
	},
	"ClusterEdit": {
		OperationID:  "ClusterEdit",
		Method:       "POST",
		PathTemplate: "/cluster/{id}",
		PathParams:   []string{"id"},
	},
	"ClusterBackupCreate": {
		OperationID:  "ClusterBackupCreate",
		Method:       "POST",
		PathTemplate: "/cluster/{id}/backup",
		PathParams:   []string{"id"},
	},
	"ClusterRemove": {
		OperationID:  "ClusterRemove",
		Method:       "DELETE",
		PathTemplate: "/cluster/{id}/{terminate}",
		PathParams:   []string{"id", "terminate"},
	},
	"ClusterSettingList": {
		OperationID:  "ClusterSettingList",
		Method:       "GET",
		PathTemplate: "/cluster/{cluster}/settings",
		PathParams:   []string{"cluster"},
	},
	"ClusterSettingAdd": {
		OperationID:  "ClusterSettingAdd",
		Method:       "POST",
		PathTemplate: "/cluster/{cluster}/settings",
		PathParams:   []string{"cluster"},
	},
	"ClusterSettingEdit": {
		OperationID:  "ClusterSettingEdit",
		Method:       "POST",
		PathTemplate: "/cluster-setting/{id}",
		PathParams:   []string{"id"},
	},
	"ClusterSettingRemove": {
		OperationID:  "ClusterSettingRemove",
		Method:       "DELETE",
		PathTemplate: "/cluster-setting/{id}",
		PathParams:   []string{"id"},
	},
	"ProfileList": {
		OperationID:  "ProfileList",
		Method:       "GET",
		PathTemplate: "/cluster/{cluster}/profiles",
		PathParams:   []string{"cluster"},
	},
	"ProfileAdd": {
		OperationID:  "ProfileAdd",
		Method:       "POST",
		PathTemplate: "/cluster/{cluster}/profiles",
		PathParams:   []string{"cluster"},
	},
	"ProfileEdit": {
		OperationID:  "ProfileEdit",
		Method:       "POST",
		PathTemplate: "/profile/{id}",
		PathParams:   []string{"id"},
	},
	"ProfileRemove": {
		OperationID:  "ProfileRemove",
		Method:       "DELETE",
		PathTemplate: "/profile/{id}",
		PathParams:   []string{"id"},
	},
	"ProfileSettingsList": {
		OperationID:  "ProfileSettingsList",
		Method:       "GET",
		PathTemplate: "/profile/{profile}/settings",
		PathParams:   []string{"profile"},
	},
	"ProfileSettingsAdd": {
		OperationID:  "ProfileSettingsAdd",
		Method:       "POST",
		PathTemplate: "/profile/{profile}/settings",
		PathParams:   []string{"profile"},
	},
	"ProfileSettingsEdit": {
		OperationID:  "ProfileSettingsEdit",
		Method:       "POST",
		PathTemplate: "/setting/{id}",
		PathParams:   []string{"id"},
	},
	"ProfileSettingsRemove": {
		OperationID:  "ProfileSettingsRemove",
		Method:       "DELETE",
		PathTemplate: "/setting/{id}",
		PathParams:   []string{"id"},
	},
	"DbuserList": {
		OperationID:  "DbuserList",
		Method:       "GET",
		PathTemplate: "/cluster/{cluster}/users",
		PathParams:   []string{"cluster"},
	},
	"DbuserAdd": {
		OperationID:  "DbuserAdd",
		Method:       "POST",
		PathTemplate: "/cluster/{cluster}/users",
		PathParams:   []string{"cluster"},
	},
	"DbuserEditSql": {
		OperationID:  "DbuserEditSql",
		Method:       "POST",
		PathTemplate: "/cluster/{cluster}/user/{id}",
		PathParams:   []string{"cluster", "id"},
	},
	"DbuserRemoveSql": {
		OperationID:  "DbuserRemoveSql",
		Method:       "DELETE",
		PathTemplate: "/cluster/{cluster}/user/{id}",
		PathParams:   []string{"cluster", "id"},
	},
	"DbuserEdit": {
		OperationID:  "DbuserEdit",
		Method:       "POST",
		PathTemplate: "/user/{id}",
		PathParams:   []string{"id"},
	},
	"ClickhouseKeeperLaunch": {
		OperationID:  "ClickhouseKeeperLaunch",
		Method:       "POST",
		PathTemplate: "/environment/{environment}/keepers",
		PathParams:   []string{"environment"},
	},
	"ClickhouseKeeperList": {
		OperationID:  "ClickhouseKeeperList",
		Method:       "GET",
		PathTemplate: "/environment/{environment}/keepers",
		PathParams:   []string{"environment"},
	},
	"ClickhouseKeeperEdit": {
		OperationID:  "ClickhouseKeeperEdit",
		Method:       "POST",
		PathTemplate: "/environment/{environment}/keeper/{name}",
		PathParams:   []string{"environment", "name"},
	},
	"ClickhouseKeeperDelete": {
		OperationID:  "ClickhouseKeeperDelete",
		Method:       "DELETE",
		PathTemplate: "/environment/{environment}/keeper/{name}",
		PathParams:   []string{"environment", "name"},
	},
	"ClickhouseKeeperStatus": {
		OperationID:  "ClickhouseKeeperStatus",
		Method:       "GET",
		PathTemplate: "/environment/{environment}/keeper/{name}/status",
		PathParams:   []string{"environment", "name"},
	},
	"NodeTypeAdd": {
		OperationID:  "NodeTypeAdd",
		Method:       "POST",
		PathTemplate: "/environment/{environment}/nodetypes",
		PathParams:   []string{"environment"},
	},
	"NodeTypeEdit": {
		OperationID:  "NodeTypeEdit",
		Method:       "POST",
		PathTemplate: "/nodetype/{id}",
		PathParams:   []string{"id"},
	},
	"NodeTypeRemove": {
		OperationID:  "NodeTypeRemove",
		Method:       "DELETE",
		PathTemplate: "/nodetype/{id}",
		PathParams:   []string{"id"},
	},
	"EnvironmentList": {
		OperationID:  "EnvironmentList",
		Method:       "GET",
		PathTemplate: "/environments",
		PathParams:   nil,
	},
	"NodeTypeList": {
		OperationID:  "NodeTypeList",
		Method:       "GET",
		PathTemplate: "/environment/{environment}/nodetypes",
		PathParams:   []string{"environment"},
	},
	"CloudOptions": {
		OperationID:  "CloudOptions",
		Method:       "GET",
		PathTemplate: "/cloud/{environment}/options",
		PathParams:   []string{"environment"},
	},
	"EnvironmentRequest": {
		OperationID:  "EnvironmentRequest",
		Method:       "POST",
		PathTemplate: "/environments/request",
		PathParams:   nil,
	},
	"EnvironmentShow": {
		OperationID:  "EnvironmentShow",
		Method:       "GET",
		PathTemplate: "/environment/{id}",
		PathParams:   []string{"id"},
	},
	"EnvironmentEdit": {
		OperationID:  "EnvironmentEdit",
		Method:       "POST",
		PathTemplate: "/environment/{id}",
		PathParams:   []string{"id"},
	},
	"EnvironmentCloudCheck": {
		OperationID:  "EnvironmentCloudCheck",
		Method:       "GET",
		PathTemplate: "/environment/{id}/acc-check",
		PathParams:   []string{"id"},
	},
	"CloudOptionsGlobal": {
		OperationID:  "CloudOptionsGlobal",
		Method:       "GET",
		PathTemplate: "/cloud/options",
		PathParams:   nil,
	},
}

// Operation ID constants. Referencing these from the client gives a
// compile-time guarantee the operation is in the generated registry.
const (
	OpClusterLaunch          = "ClusterLaunch"
	OpClusterList            = "ClusterList"
	OpClusterShow            = "ClusterShow"
	OpClusterStatus          = "ClusterStatus"
	OpClusterRescale         = "ClusterRescale"
	OpClusterUpgrade         = "ClusterUpgrade"
	OpClusterEdit            = "ClusterEdit"
	OpClusterBackupCreate    = "ClusterBackupCreate"
	OpClusterRemove          = "ClusterRemove"
	OpClusterSettingList     = "ClusterSettingList"
	OpClusterSettingAdd      = "ClusterSettingAdd"
	OpClusterSettingEdit     = "ClusterSettingEdit"
	OpClusterSettingRemove   = "ClusterSettingRemove"
	OpProfileList            = "ProfileList"
	OpProfileAdd             = "ProfileAdd"
	OpProfileEdit            = "ProfileEdit"
	OpProfileRemove          = "ProfileRemove"
	OpProfileSettingsList    = "ProfileSettingsList"
	OpProfileSettingsAdd     = "ProfileSettingsAdd"
	OpProfileSettingsEdit    = "ProfileSettingsEdit"
	OpProfileSettingsRemove  = "ProfileSettingsRemove"
	OpDbuserList             = "DbuserList"
	OpDbuserAdd              = "DbuserAdd"
	OpDbuserEditSql          = "DbuserEditSql"
	OpDbuserRemoveSql        = "DbuserRemoveSql"
	OpDbuserEdit             = "DbuserEdit"
	OpClickhouseKeeperLaunch = "ClickhouseKeeperLaunch"
	OpClickhouseKeeperList   = "ClickhouseKeeperList"
	OpClickhouseKeeperEdit   = "ClickhouseKeeperEdit"
	OpClickhouseKeeperDelete = "ClickhouseKeeperDelete"
	OpClickhouseKeeperStatus = "ClickhouseKeeperStatus"
	OpNodeTypeAdd            = "NodeTypeAdd"
	OpNodeTypeEdit           = "NodeTypeEdit"
	OpNodeTypeRemove         = "NodeTypeRemove"
	OpEnvironmentList        = "EnvironmentList"
	OpNodeTypeList           = "NodeTypeList"
	OpCloudOptions           = "CloudOptions"
	OpEnvironmentRequest     = "EnvironmentRequest"
	OpEnvironmentShow        = "EnvironmentShow"
	OpEnvironmentEdit        = "EnvironmentEdit"
	OpEnvironmentCloudCheck  = "EnvironmentCloudCheck"
	OpCloudOptionsGlobal     = "CloudOptionsGlobal"
)
