// Copyright (c) Gorgias, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/specgen; DO NOT EDIT.
// Source: internal/acm/wire/reference.json (vendored OpenAPI spec).
// Regenerate with: go generate ./...

package wire

import "encoding/json"

// These are faithful WIRE types: scalar types follow the spec's loose
// typing (string-ints and 0|1 ints both arrive as json.Number; bare
// objects with no sub-schema are json.RawMessage). The hand-written
// domain layer coerces the known scalar fields and (TODO(spike))
// strongly types the opaque-object fields.

// Cluster is the wire representation of components.schemas.Cluster.
type Cluster struct {
	ActionSchedule            json.RawMessage `json:"actionSchedule,omitempty"`
	AdminPass                 string          `json:"adminPass,omitempty"`
	AlertsEmail               string          `json:"alertsEmail,omitempty"`
	AlertsSettings            json.RawMessage `json:"alertsSettings,omitempty"`
	AlternateEndpoints        json.RawMessage `json:"alternateEndpoints,omitempty"`
	AltinityOptions           json.RawMessage `json:"altinityOptions,omitempty"`
	AltinityPassword          string          `json:"altinityPassword,omitempty"`
	AltinitySupport           string          `json:"altinitySupport,omitempty"`
	Annotations               json.RawMessage `json:"annotations,omitempty"`
	BackupConfigModifications json.RawMessage `json:"backupConfigModifications,omitempty"`
	BackupOptions             json.RawMessage `json:"backupOptions,omitempty"`
	BackupScheduleUpdate      string          `json:"backupScheduleUpdate,omitempty"`
	BackupSource              string          `json:"backupSource,omitempty"`
	ChGuardSettings           json.RawMessage `json:"chGuardSettings,omitempty"`
	CheckTime                 string          `json:"checkTime,omitempty"`
	CustomLBAnnotations       json.RawMessage `json:"customLBAnnotations,omitempty"`
	DatadogSettings           json.RawMessage `json:"datadogSettings,omitempty"`
	Endpoint                  string          `json:"endpoint,omitempty"`
	EndpointHTTP              string          `json:"endpointHTTP,omitempty"`
	EndpointsEnabled          json.RawMessage `json:"endpointsEnabled,omitempty"`
	Environment               *Environment    `json:"environment,omitempty"`
	ID                        Number          `json:"id,omitempty"`
	IDEnvironment             Number          `json:"id_environment,omitempty"`
	IDInitialAction           Number          `json:"id_initialAction,omitempty"`
	IDOwner                   Number          `json:"id_owner,omitempty"`
	IDParent                  Number          `json:"id_parent,omitempty"`
	IDZookeeper               Number          `json:"id_zookeeper,omitempty"`
	InitialAction             json.RawMessage `json:"initialAction,omitempty"`
	KeeperName                string          `json:"keeperName,omitempty"`
	LatestBackupTime          string          `json:"latestBackupTime,omitempty"`
	Locked                    Bool            `json:"locked,omitempty"`
	MetricsUpdateTime         string          `json:"metricsUpdateTime,omitempty"`
	MoveFactor                Number          `json:"moveFactor,omitempty"`
	MysqlPort                 Number          `json:"mysqlPort,omitempty"`
	MysqlProtocol             Bool            `json:"mysqlProtocol,omitempty"`
	Name                      string          `json:"name,omitempty"`
	Nodes                     json.RawMessage `json:"nodes,omitempty"`
	ObjectStorages            json.RawMessage `json:"objectStorages,omitempty"`
	Options                   json.RawMessage `json:"options,omitempty"`
	Owner                     json.RawMessage `json:"owner,omitempty"`
	Parent                    *Cluster        `json:"parent,omitempty"`
	ProfileSyncTime           string          `json:"profileSyncTime,omitempty"`
	ReplicaSource             string          `json:"replicaSource,omitempty"`
	Replicas                  string          `json:"replicas,omitempty"`
	Role                      string          `json:"role,omitempty"`
	SecretHandler             string          `json:"secretHandler,omitempty"`
	Secure                    Bool            `json:"secure,omitempty"`
	Shards                    string          `json:"shards,omitempty"`
	StartupTime               Number          `json:"startupTime,omitempty"`
	State                     string          `json:"state,omitempty"`
	Status                    string          `json:"status,omitempty"`
	StoragePolicy             string          `json:"storagePolicy,omitempty"`
	SystemVersion             string          `json:"systemVersion,omitempty"`
	TableSyncTime             string          `json:"tableSyncTime,omitempty"`
	Timezone                  string          `json:"timezone,omitempty"`
	TroubleshootingMode       Bool            `json:"troubleshootingMode,omitempty"`
	Type                      string          `json:"type,omitempty"`
	Uptime                    string          `json:"uptime,omitempty"`
	UptimeCheckTime           string          `json:"uptimeCheckTime,omitempty"`
	UptimeSettings            json.RawMessage `json:"uptimeSettings,omitempty"`
	ZoneAwareness             Bool            `json:"zoneAwareness,omitempty"`
	Zookeeper                 json.RawMessage `json:"zookeeper,omitempty"`
}

// DbUser is the wire representation of components.schemas.DbUser.
type DbUser struct {
	AccessManagement Bool            `json:"accessManagement,omitempty"`
	Cluster          *Cluster        `json:"cluster,omitempty"`
	Databases        json.RawMessage `json:"databases,omitempty"`
	ID               Number          `json:"id,omitempty"`
	IDCluster        Number          `json:"id_cluster,omitempty"`
	IDProfile        Number          `json:"id_profile,omitempty"`
	IDQuota          Number          `json:"id_quota,omitempty"`
	Login            string          `json:"login,omitempty"`
	Networks         json.RawMessage `json:"networks,omitempty"`
	Password         string          `json:"password,omitempty"`
	Profile          *Profile        `json:"profile,omitempty"`
	Quota            json.RawMessage `json:"quota,omitempty"`
}

// Profile is the wire representation of components.schemas.Profile.
type Profile struct {
	Cluster     *Cluster `json:"cluster,omitempty"`
	Description string   `json:"description,omitempty"`
	ID          Number   `json:"id,omitempty"`
	IDCluster   Number   `json:"id_cluster,omitempty"`
	Name        string   `json:"name,omitempty"`
}

// ProfileSetting is the wire representation of components.schemas.ProfileSetting.
type ProfileSetting struct {
	Description string   `json:"description,omitempty"`
	ID          Number   `json:"id,omitempty"`
	IDProfile   Number   `json:"id_profile,omitempty"`
	Name        string   `json:"name,omitempty"`
	Parsed      Bool     `json:"parsed,omitempty"`
	Profile     *Profile `json:"profile,omitempty"`
	Value       string   `json:"value,omitempty"`
}

// Node is the wire representation of components.schemas.Node.
type Node struct {
	AWSOptions    json.RawMessage `json:"awsOptions,omitempty"`
	CheckTime     string          `json:"checkTime,omitempty"`
	ContainerID   string          `json:"containerId,omitempty"`
	DataPath      string          `json:"dataPath,omitempty"`
	Environment   *Environment    `json:"environment,omitempty"`
	Host          string          `json:"host,omitempty"`
	HTTPPort      Number          `json:"httpPort,omitempty"`
	HTTPPortTLS   Number          `json:"httpPortTLS,omitempty"`
	ID            Number          `json:"id,omitempty"`
	IDEnvironment Number          `json:"id_environment,omitempty"`
	Metrics       json.RawMessage `json:"metrics,omitempty"`
	Pass          string          `json:"pass,omitempty"`
	Port          Number          `json:"port,omitempty"`
	PortTLS       Number          `json:"portTLS,omitempty"`
	PublicHost    string          `json:"publicHost,omitempty"`
	SSHHost       string          `json:"sshHost,omitempty"`
	SSHKey        string          `json:"sshKey,omitempty"`
	SSHPass       string          `json:"sshPass,omitempty"`
	SSHPort       string          `json:"sshPort,omitempty"`
	SSHUser       string          `json:"sshUser,omitempty"`
	State         string          `json:"state,omitempty"`
	Status        string          `json:"status,omitempty"`
	Terminate     string          `json:"terminate,omitempty"`
	Type          string          `json:"type,omitempty"`
	User          string          `json:"user,omitempty"`
	Version       string          `json:"version,omitempty"`
	VolumeID      string          `json:"volumeId,omitempty"`
}

// Environment is the wire representation of components.schemas.Environment.
type Environment struct {
	AutoPush                   Number          `json:"autoPush,omitempty"`
	AutoZkPush                 Number          `json:"autoZkPush,omitempty"`
	AWSKey                     string          `json:"awsKey,omitempty"`
	AWSKeyPairName             string          `json:"awsKeyPairName,omitempty"`
	AWSPrivateKey              string          `json:"awsPrivateKey,omitempty"`
	AWSSecretKey               string          `json:"awsSecretKey,omitempty"`
	AWSSettings                string          `json:"awsSettings,omitempty"`
	AWSSettingsAuto            Bool            `json:"awsSettingsAuto,omitempty"`
	BackupOptions              json.RawMessage `json:"backupOptions,omitempty"`
	Created                    string          `json:"created,omitempty"`
	DashboardURL               string          `json:"dashboardUrl,omitempty"`
	DatadogPassword            string          `json:"datadogPassword,omitempty"`
	DatadogSettings            json.RawMessage `json:"datadogSettings,omitempty"`
	DisplayName                string          `json:"displayName,omitempty"`
	Domain                     string          `json:"domain,omitempty"`
	ExternalDNS                Number          `json:"externalDNS,omitempty"`
	HipaaCompliant             Bool            `json:"hipaaCompliant,omitempty"`
	HostedByAltinity           Bool            `json:"hostedByAltinity,omitempty"`
	ID                         Number          `json:"id,omitempty"`
	IDOwner                    Number          `json:"id_owner,omitempty"`
	IDParent                   Number          `json:"id_parent,omitempty"`
	ImageRegistry              string          `json:"imageRegistry,omitempty"`
	InternalEncryption         Bool            `json:"internalEncryption,omitempty"`
	KubeAPIURL                 string          `json:"kubeAPIUrl,omitempty"`
	KubeAuthOptions            json.RawMessage `json:"kubeAuthOptions,omitempty"`
	KubeCHOVersion             string          `json:"kubeCHOVersion,omitempty"`
	KubeCanUninstall           Bool            `json:"kubeCanUninstall,omitempty"`
	KubeCheck                  string          `json:"kubeCheck,omitempty"`
	KubeLBType                 string          `json:"kubeLBType,omitempty"`
	KubeManagedPVs             Bool            `json:"kubeManagedPVs,omitempty"`
	KubeNamespace              string          `json:"kubeNamespace,omitempty"`
	KubeNamespaceManage        Bool            `json:"kubeNamespaceManage,omitempty"`
	KubeNodeLabel              string          `json:"kubeNodeLabel,omitempty"`
	KubeProvider               string          `json:"kubeProvider,omitempty"`
	KubeStartupTime            Number          `json:"kubeStartupTime,omitempty"`
	KubeToken                  string          `json:"kubeToken,omitempty"`
	KubeZoneKey                string          `json:"kubeZoneKey,omitempty"`
	ListenCheck                string          `json:"listenCheck,omitempty"`
	LoadBalancePROXYProtocolV2 Bool            `json:"loadBalancePROXYProtocolV2,omitempty"`
	LogsOptions                json.RawMessage `json:"logsOptions,omitempty"`
	LogsStorage                json.RawMessage `json:"logsStorage,omitempty"`
	Managed                    Bool            `json:"managed,omitempty"`
	Monitoring                 Bool            `json:"monitoring,omitempty"`
	MonitoringCheck            string          `json:"monitoringCheck,omitempty"`
	MonitoringInfo             json.RawMessage `json:"monitoringInfo,omitempty"`
	MonitoringURL              string          `json:"monitoringUrl,omitempty"`
	Name                       string          `json:"name,omitempty"`
	NormalizedName             string          `json:"normalizedName,omitempty"`
	Notes                      string          `json:"notes,omitempty"`
	Options                    json.RawMessage `json:"options,omitempty"`
	Owner                      json.RawMessage `json:"owner,omitempty"`
	Parent                     *Environment    `json:"parent,omitempty"`
	Pass                       string          `json:"pass,omitempty"`
	PrivateLB                  Bool            `json:"privateLB,omitempty"`
	PublicLB                   Bool            `json:"publicLB,omitempty"`
	Remote                     Bool            `json:"remote,omitempty"`
	ResourceLimits             json.RawMessage `json:"resourceLimits,omitempty"`
	SniProxyForCH              Bool            `json:"sniProxyForCH,omitempty"`
	SSLCertificateARN          string          `json:"sslCertificateARN,omitempty"`
	State                      string          `json:"state,omitempty"`
	Status                     string          `json:"status,omitempty"`
	Type                       string          `json:"type,omitempty"`
	UpdatedAtBackend           string          `json:"updatedAtBackend,omitempty"`
	UseKeeper                  Bool            `json:"useKeeper,omitempty"`
	User                       string          `json:"user,omitempty"`
	UserAgent                  string          `json:"userAgent,omitempty"`
	VpcEndpoints               Bool            `json:"vpcEndpoints,omitempty"`
}

// NodeType is the wire representation of components.schemas.NodeType.
type NodeType struct {
	Capacity      Number          `json:"capacity,omitempty"`
	Code          string          `json:"code,omitempty"`
	CPU           Number          `json:"cpu,omitempty"`
	Environment   *Environment    `json:"environment,omitempty"`
	ExtraSpec     json.RawMessage `json:"extraSpec,omitempty"`
	ID            Number          `json:"id,omitempty"`
	IDEnvironment Number          `json:"id_environment,omitempty"`
	IsSpot        Bool            `json:"isSpot,omitempty"`
	Memory        Number          `json:"memory,omitempty"`
	Name          string          `json:"name,omitempty"`
	NodeSelector  json.RawMessage `json:"nodeSelector,omitempty"`
	Scope         string          `json:"scope,omitempty"`
	StorageClass  string          `json:"storageClass,omitempty"`
	Tolerations   json.RawMessage `json:"tolerations,omitempty"`
}

// CHKeeper is the wire representation of components.schemas.CHKeeper.
type CHKeeper struct {
	CPULimits       Number          `json:"cpuLimits,omitempty"`
	CPURequests     Number          `json:"cpuRequests,omitempty"`
	Ha              Bool            `json:"ha,omitempty"`
	Image           string          `json:"image,omitempty"`
	InstanceType    string          `json:"instanceType,omitempty"`
	Maintenance     Bool            `json:"maintenance,omitempty"`
	Name            string          `json:"name,omitempty"`
	Restart         string          `json:"restart,omitempty"`
	Settings        json.RawMessage `json:"settings,omitempty"`
	Stop            Bool            `json:"stop,omitempty"`
	ZoneTopologyKey string          `json:"zoneTopologyKey,omitempty"`
	Zones           []string        `json:"zones,omitempty"`
}
